<a href="https://colab.research.google.com/github/kaanygl/air_quality_dataset_analysis/blob/main/processed_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/bv2hvm4pmz-3.zip

--2024-11-16 20:42:37--  https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/bv2hvm4pmz-3.zip
Resolving prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com (prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com)... 52.218.102.16, 3.5.67.172, 3.5.69.211, ...
Connecting to prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com (prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com)|52.218.102.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1340049458 (1.2G) [application/zip]
Saving to: ‘bv2hvm4pmz-3.zip’

bv2hvm4pmz-3.zip    100%[===================>]   1.25G  39.5MB/s    in 33s

2024-11-16 20:43:11 (38.5 MB/s) - ‘bv2hvm4pmz-3.zip’ saved [1340049458/1340049458]

In [2]:
!unzip /content/bv2hvm4pmz-3.zip

Archive:  /content/bv2hvm4pmz-3.zip
  inflating: Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_gold.csv
  inflating: Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_silver.csv
  inflating: Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_brown.csv

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_brown = pd.read_csv("/content/Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_brown.csv",header=None)
df_brown = df_brown.drop(index=0).reset_index(drop=True)

In [3]:
df_brown

                                                         0
0        1;node-air-brown;2015;0.251883;659.087;29.3526...
1        2;node-air-brown;1950;0.243757;658.184;29.366;...
2        3;node-air-brown;1995;0.249133;655.991;29.3927...
3        4;node-air-brown;2010;0.251258;655.74;29.3526;...
4        5;node-air-brown;1993;0.249133;655.774;29.366;...
...                                                    ...
9937006  10162291;node-air-brown;2237;0.279634;560.587;...
9937007  10162292;node-air-brown;2221;0.274383;560.002;...
9937008  10162293;node-air-brown;2209;0.276133;559.953;...
9937009  10162294;node-air-brown;2217;0.277008;559.799;...
9937010  10162295;node-air-brown;2222;0.277758;559.123;...

[9937011 rows x 1 columns]

In [4]:
split_data_brown = df_brown.iloc[:, 0].apply(lambda x: x.split(";"))

In [5]:

columns_brown = "id_measure;node_id;ads1115_value;ads1115_voltage;scd30_co2;scd30_temp;scd30_hum;sps30_pm05_count;sps30_pm1_count;sps30_pm1_ug;sps30_pm25_count;sps30_pm25_ug;sps30_pm4_count;sps30_pm4_ug;sps30_pm10_count;sps30_pm10_ug;sps30_pm_typ;ts_insertion"

column_names_brown = columns_brown.split(";")

print(column_names_brown)

['id_measure', 'node_id', 'ads1115_value', 'ads1115_voltage', 'scd30_co2', 'scd30_temp', 'scd30_hum', 'sps30_pm05_count', 'sps30_pm1_count', 'sps30_pm1_ug', 'sps30_pm25_count', 'sps30_pm25_ug', 'sps30_pm4_count', 'sps30_pm4_ug', 'sps30_pm10_count', 'sps30_pm10_ug', 'sps30_pm_typ', 'ts_insertion']

In [6]:
split_data_brown

0          [1, node-air-brown, 2015, 0.251883, 659.087, 2...
1          [2, node-air-brown, 1950, 0.243757, 658.184, 2...
2          [3, node-air-brown, 1995, 0.249133, 655.991, 2...
3          [4, node-air-brown, 2010, 0.251258, 655.74, 29...
4          [5, node-air-brown, 1993, 0.249133, 655.774, 2...
                                 ...
9937006    [10162291, node-air-brown, 2237, 0.279634, 560...
9937007    [10162292, node-air-brown, 2221, 0.274383, 560...
9937008    [10162293, node-air-brown, 2209, 0.276133, 559...
9937009    [10162294, node-air-brown, 2217, 0.277008, 559...
9937010    [10162295, node-air-brown, 2222, 0.277758, 559...
Name: 0, Length: 9937011, dtype: object

In [7]:
reformatted_df_brown = pd.DataFrame(split_data_brown.tolist(), columns=column_names_brown)

In [8]:
reformatted_df_brown

,id_measure,node_id,ads1115_value,ads1115_voltage,scd30_co2,scd30_temp,scd30_hum,sps30_pm05_count,sps30_pm1_count,sps30_pm1_ug,sps30_pm25_count,sps30_pm25_ug,sps30_pm4_count,sps30_pm4_ug,sps30_pm10_count,sps30_pm10_ug,sps30_pm_typ,ts_insertion
0,1,node-air-brown,2015,0.251883,659.087,29.3526,51.7715,43.0549,50.381,6.32602,50.487,6.68953,50.4978,6.68954,50.5058,6.68954,0.424354,2022-10-27 10:57:14
1,2,node-air-brown,1950,0.243757,658.184,29.366,51.799,43.5107,50.9143,6.39299,51.0214,6.76034,51.0324,6.76035,51.0405,6.76035,0.427185,2022-10-27 10:57:17
2,3,node-air-brown,1995,0.249133,655.991,29.3927,51.8387,44.1547,51.6679,6.48762,51.7767,6.86041,51.7878,6.86042,51.796,6.86041,0.428009,2022-10-27 10:57:19
3,4,node-air-brown,2010,0.251258,655.74,29.3526,51.8906,44.2329,51.7594,6.4991,51.8683,6.87255,51.8794,6.87256,51.8877,6.87256,0.426949,2022-10-27 10:57:21
4,5,node-air-brown,1993,0.249133,655.774,29.366,51.8448,44.4443,52.0068,6.53017,52.1163,6.90541,52.1274,6.90541,52.1357,6.90541,0.428101,2022-10-27 10:57:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9937006,10162291,node-air-brown,2237,0.279634,560.587,28.0709,50.032,14.1197,16.5222,2.07459,16.557,2.1938,16.5605,2.1938,16.5631,2.1938,0.396032,2023-10-07 22:46:52
9937007,10162292,node-air-brown,2221,0.274383,560.002,28.0415,50.0763,13.98,16.3588,2.05407,16.3932,2.17211,16.3968,2.17211,16.3994,2.17211,0.397891,2023-10-07 22:46:55
9937008,10162293,node-air-brown,2209,0.276133,559.953,28.0842,50.1312,13.8982,16.2631,2.04205,16.2973,2.15939,16.3008,2.15939,16.3034,2.15939,0.398572,2023-10-07 22:46:57
9937009,10162294,node-air-brown,2217,0.277008,559.799,28.0415,49.9451,14.0433,16.4329,2.06338,16.4675,2.18194,16.471,2.18195,16.4736,2.18194,0.399749,2023-10-07 22:46:59
9937010,10162295,node-air-brown,2222,0.277758,559.123,28.0709,49.8428,14.0552,16.4467,2.06511,16.4813,2.18378,16.4849,2.18378,16.4875,2.18378,0.400503,2023-10-07 22:47:01

In [9]:
column_dtypes = {
    'id_measure': int,
    'node_id': str,
    'ads1115_value': int,
    'ads1115_voltage': float,
    'scd30_co2': float,
    'scd30_temp': float,
    'scd30_hum': float,
    'sps30_pm05_count': float,
    'sps30_pm1_count': float,
    'sps30_pm1_ug': float,
    'sps30_pm25_count': float,
    'sps30_pm25_ug': float,
    'sps30_pm4_count': float,
    'sps30_pm4_ug': float,
    'sps30_pm10_count': float,
    'sps30_pm10_ug': float,
    'sps30_pm_typ': float,
    'ts_insertion': str
}

In [15]:
for i in reformatted_df_brown.columns:
  if type(i) == float:
    reformatted_df_brown[i] = reformatted_df_brown[i].replace('NULL', np.nan)
    reformatted_df_brown[i] = reformatted_df_brown[i].astype(float)
  elif type(i) == int:
    reformatted_df_brown[i] = reformatted_df_brown[i].replace('NULL', np.nan)
    reformatted_df_brown[i] = reformatted_df_brown[i].astype(int)
  else:
    reformatted_df_brown[i] = reformatted_df_brown[i].replace('NULL', np.nan)
    reformatted_df_brown[i] = reformatted_df_brown[i].astype(str)

In [17]:
reformatted_df_brown['id_measure'] = pd.to_numeric(reformatted_df_brown['id_measure'], errors='coerce')
reformatted_df_brown['id_measure'] = reformatted_df_brown['id_measure'].fillna(0).astype(int)

In [25]:
reformatted_df_brown = reformatted_df_brown.astype(column_dtypes)

In [11]:
output_file_brown = "processed_brown.csv"
reformatted_df_brown.to_csv(output_file_brown, index=False)

gold

In [12]:
df_gold = pd.read_csv("/content/Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_gold.csv", header=None)

In [13]:
df_gold = df_gold.drop(index=0).reset_index(drop=True)

In [14]:
split_data_gold = df_gold.iloc[:, 0].apply(lambda x: x.split(";"))

In [15]:
split_data_gold

0          [1, node-air-gold, 1950, 0.243757, 606.316, 29...
1          [2, node-air-gold, 1997, 0.249633, 605.303, 29...
2          [3, node-air-gold, 1997, 0.249633, 605.58, 29....
3          [4, node-air-gold, 1977, 0.247133, 605.191, 29...
4          [5, node-air-gold, 1957, 0.244632, 603.975, 29...
                                 ...
7105446    [7490026, node-air-gold, 1663, 0.207881, 713.6...
7105447    [7490027, node-air-gold, 1664, 0.208006, 713.5...
7105448    [7490028, node-air-gold, 1645, 0.205631, 713.1...
7105449    [7490029, node-air-gold, 1664, 0.207881, 711.3...
7105450    [7490030, node-air-gold, 1656, 0.207006, 710.7...
Name: 0, Length: 7105451, dtype: object

In [16]:
columns_gold = "id_measure;node_id;ads1115_value;ads1115_voltage;scd30_co2;scd30_temp;scd30_hum;sps30_pm05_count;sps30_pm1_count;sps30_pm1_ug;sps30_pm25_count;sps30_pm25_ug;sps30_pm4_count;sps30_pm4_ug;sps30_pm10_count;sps30_pm10_ug;sps30_pm_typ;ts_insertion"

column_names_gold = columns_gold.split(";")

print(column_names_gold)

['id_measure', 'node_id', 'ads1115_value', 'ads1115_voltage', 'scd30_co2', 'scd30_temp', 'scd30_hum', 'sps30_pm05_count', 'sps30_pm1_count', 'sps30_pm1_ug', 'sps30_pm25_count', 'sps30_pm25_ug', 'sps30_pm4_count', 'sps30_pm4_ug', 'sps30_pm10_count', 'sps30_pm10_ug', 'sps30_pm_typ', 'ts_insertion']

In [26]:
reformatted_df_gold = pd.DataFrame(split_data_gold.tolist(), columns=column_names_gold)

NameError: name 'split_data_gold' is not defined

In [ ]:
reformatted_df_gold = reformatted_df_gold.astype(column_dtypes)

In [ ]:
for i in reformatted_df_gold.columns:
  if type(i) == float:
    reformatted_df_gold[i] = reformatted_df_gold[i].replace('NULL', np.nan)
    reformatted_df_gold[i] = reformatted_df_gold[i].astype(float)
  elif type(i) == int:
    reformatted_df_gold[i] = reformatted_df_gold[i].replace('NULL', np.nan)
    reformatted_df_gold[i] = reformatted_df_gold[i].astype(int)
  else:
    reformatted_df_gold[i] = reformatted_df_gold[i].replace('NULL', np.nan)
    reformatted_df_gold[i] = reformatted_df_gold[i].astype(str)

In [ ]:
reformatted_df_gold['id_measure'] = pd.to_numeric(reformatted_df_gold['id_measure'], errors='coerce')
reformatted_df_gold['id_measure'] = reformatted_df_gold['id_measure'].fillna(0).astype(int)

In [ ]:
reformatted_df_brown = reformatted_df_brown.astype(column_dtypes)

In [19]:
output_file_gold = "processed_gold.csv"
reformatted_df_gold.to_csv(output_file_gold, index=False)

silver

In [20]:
df_silver = pd.read_csv("/content/Indoor Air Quality Monitoring @ Brindisi Airport/complete_measure_node_airport_silver.csv", header=None)

In [21]:
df_silver = df_silver.drop(index=0).reset_index(drop=True)

In [22]:
split_data_silver  = df_silver .iloc[:, 0].apply(lambda x: x.split(";"))

In [23]:
split_data_silver

0           [1, node-air-silver, 2270, 0.283759, 488.513, ...
1           [2, node-air-silver, 2295, 0.286884, 488.629, ...
2           [3, node-air-silver, 2352, 0.294009, 488.621, ...
3           [4, node-air-silver, 2405, 0.300634, 488.153, ...
4           [5, node-air-silver, 2443, 0.305384, 488.058, ...
                                  ...
11135469    [11454424, node-air-silver, 2538, 0.317635, 64...
11135470    [11454425, node-air-silver, 2546, 0.317885, 64...
11135471    [11454426, node-air-silver, 2580, 0.32251, 642...
11135472    [11454427, node-air-silver, 2592, 0.32401, 642...
11135473    [11454428, node-air-silver, 2553, 0.319385, 64...
Name: 0, Length: 11135474, dtype: object

In [24]:
columns_silver = "id_measure;node_id;ads1115_value;ads1115_voltage;scd30_co2;scd30_temp;scd30_hum;sps30_pm05_count;sps30_pm1_count;sps30_pm1_ug;sps30_pm25_count;sps30_pm25_ug;sps30_pm4_count;sps30_pm4_ug;sps30_pm10_count;sps30_pm10_ug;sps30_pm_typ;ts_insertion"

column_names_silver = columns_silver.split(";")

print(column_names_silver)

['id_measure', 'node_id', 'ads1115_value', 'ads1115_voltage', 'scd30_co2', 'scd30_temp', 'scd30_hum', 'sps30_pm05_count', 'sps30_pm1_count', 'sps30_pm1_ug', 'sps30_pm25_count', 'sps30_pm25_ug', 'sps30_pm4_count', 'sps30_pm4_ug', 'sps30_pm10_count', 'sps30_pm10_ug', 'sps30_pm_typ', 'ts_insertion']

In [25]:
reformatted_df_silver = pd.DataFrame(split_data_silver.tolist(), columns=column_names_silver)

In [26]:
reformatted_df_silver

,id_measure,node_id,ads1115_value,ads1115_voltage,scd30_co2,scd30_temp,scd30_hum,sps30_pm05_count,sps30_pm1_count,sps30_pm1_ug,sps30_pm25_count,sps30_pm25_ug,sps30_pm4_count,sps30_pm4_ug,sps30_pm10_count,sps30_pm10_ug,sps30_pm_typ,ts_insertion
0,1,node-air-silver,2270,0.283759,488.513,28.1029,55.04,40.8925,47.498,5.96961,47.6426,6.31264,47.6508,6.31264,47.6574,6.31265,0.412753,2022-10-27 10:23:07
1,2,node-air-silver,2295,0.286884,488.629,28.1029,55.04,40.6003,47.1587,5.92697,47.3022,6.26754,47.3104,6.26754,47.3169,6.26755,0.417791,2022-10-27 10:23:09
2,3,node-air-silver,2352,0.294009,488.621,28.0896,55.0385,40.6168,47.1778,5.92936,47.3213,6.27008,47.3295,6.27008,47.336,6.27008,0.419977,2022-10-27 10:23:11
3,4,node-air-silver,2405,0.300634,488.153,28.1163,55.0659,40.9238,47.5344,5.97419,47.6791,6.31748,47.6873,6.31748,47.6939,6.31748,0.422307,2022-10-27 10:23:13
4,5,node-air-silver,2443,0.305384,488.058,28.1029,55.0293,41.051,47.6821,5.99276,47.8273,6.33711,47.8356,6.33711,47.8421,6.33712,0.420938,2022-10-27 10:23:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11135469,11454424,node-air-silver,2538,0.317635,643.554,28.2979,43.129,42.6115,49.502,6.22209,49.657,6.58358,49.666,6.58685,49.6729,6.58852,0.472971,2023-10-13 08:04:18
11135470,11454425,node-air-silver,2546,0.317885,643.205,28.3433,43.0923,41.8509,48.6179,6.11092,48.7698,6.46569,48.7786,6.46868,48.7854,6.47021,0.475865,2023-10-13 08:04:20
11135471,11454426,node-air-silver,2580,0.32251,642.603,28.3299,43.1183,41.6934,48.436,6.08814,48.588,6.44214,48.5968,6.44558,48.6036,6.44734,0.478201,2023-10-13 08:04:22
11135472,11454427,node-air-silver,2592,0.32401,642.695,28.3299,43.2373,41.5168,48.2319,6.06258,48.3838,6.41568,48.3927,6.4196,48.3995,6.42159,0.477551,2023-10-13 08:04:25
11135473,11454428,node-air-silver,2553,0.319385,642.055,28.3566,43.3975,41.9584,48.7418,6.12641,48.8935,6.48151,48.9023,6.48404,48.9091,6.48533,0.47075,2023-10-13 08:04:27

In [ ]:
for i in reformatted_df_silver.columns:
  if type(i) == float:
    reformatted_df_silver[i] = reformatted_df_silver[i].replace('NULL', np.nan)
    reformatted_df_silver[i] = reformatted_df_silver[i].astype(float)
  elif type(i) == int:
    reformatted_df_silver[i] = reformatted_df_silver[i].replace('NULL', np.nan)
    reformatted_df_silver[i] = reformatted_df_silver[i].astype(int)
  else:
    reformatted_df_silver[i] = reformatted_df_gold[i].replace('NULL', np.nan)
    reformatted_df_silver[i] = reformatted_df_silver[i].astype(str)

In [ ]:
reformatted_df_silver['id_measure'] = pd.to_numeric(reformatted_df_silver['id_measure'], errors='coerce')
reformatted_df_silver['id_measure'] = reformatted_df_silver['id_measure'].fillna(0).astype(int)

In [ ]:
reformatted_df_brown = reformatted_df_brown.astype(column_dtypes)

In [27]:
output_file_silver = "processed_silver.csv"
reformatted_df_silver.to_csv(output_file_silver, index=False)

NameError: name 'reformatted_df_silver' is not defined

In [29]:
import zipfile
from google.colab import files

files_to_compress = ["processed_brown.csv", "processed_gold.csv", "processed_silver.csv"]
archive_name = "files_archive.zip"

with zipfile.ZipFile(archive_name, 'w') as zipf:
    for file in files_to_compress:
        zipf.write(file)

files.download(archive_name)